function [ code ] = code_database( menuselection )
%code_database by Philip Andresen (Version 23:AUGUST:2011)
%INTENDED CALLER: DNA_reader.m
%PURPOSE: This function simply returns a given DNA sequence in a
%   pre-programmed database
%INPUTS:
%   menuselection: This is the value of the dropdown menu in the DNA_reader
%       that will tell this function which code to return.
%OUTPUTS:
%   code: This is the coded string DNA sequence in case(menuselection).
%CHANGELOG:
%   Changes have not been logged as of (23:AUGUST:2011)
%External function dependencies:
%   None
switch menuselection
    case 1 %blank
        code='___';
    case 2 %H3N2 hemagglutinin (HA) EF614248.1
        code=strcat(...
            'atgaagaccatcattgctttgagctacattttctgtctggctctcggccaagaccttcca',...
            'ggaaatgacaacagcacagcaacgctgtgcctgggacatcatgcggtgccaaacggaaca',...
            'ctagtgaaaacaatcacagatgatcagattgaagtgactaatgctactgagctagttcag',...
            'agctcctcaacggggaaaatatgcaacaatcctcatcgaatccttgatggaatagactgc',...
            'acactgatagatgctctattgggggaccctcattgtgatgtttttcaaaatgagacatgg',...
            'gaccttttcgttgaacgcagcaaagctttcagcaactgttacccttatgatgtgccagat',...
            'tatgcctcccttaggtcactagttgcctcgtcaggcactctggagtttatcactgagggt',...
            'ttcacttggactggggtcactcagaatgggggaagcaatgcttgcaaaaggggacctggt',...
            'agcggttttttcagtagactgaactggttgaccaaatcaggaagcacatatccagtgctg',...
            'aacgtgactatgccaaacaatgacaattttgacaaactatacatttggggggttcaccac',...
            'ccgagcacgaaccaagaacaaaccagcctgtatgttcaagcatcagggagagtcacagtc',...
            'tctaccaggagaagccagcaaactataatcccgaatatcgagtccagaccctgggtaagg',...
            'ggtctgtctagtagaataagcatctattggacaatagttaagccgggagacgtactggta',...
            'attaatagtaatgggaacctaatcgctcctcggggttatttcaaaatgcgcactgggaaa',...
            'agctcaataatgaggtcagatgcacctattgatacctgtatttctgaatgcatcactcca',...
            'aatggaagcattcccaatgacaagccctttcaaaacgtaaacaagatcacatatggagca',...
            'tgccccaagtatgttaagcaaaacaccctgaagttggcaacagggatgcggaatgtacca',...
            'gagaaacaaactagaggcctattcggcgcaatagcaggtttcatagaaaatggttgggag',...
            'ggaatgatagacggttggtacggtttcaggcatcaaaattctgagggcacaggacaagca',...
            'gcagatcttaaaagcactcaagcagccatcgaccaaatcaatgggaaattgaacagggta',...
            'atcgagaagacgaacgagaaattccatcaaatcgaaaaggaattctcagaagtagaaggg',...
            'agaattcaggacctcgagaaatacgttgaagacactaaaatagatctctggtcttacaat',...
            'gcggagcttcttgtcgctctggagaatcaacatacaattgacctgactgactcggaaatg',...
            'aacaagctgtttgaaaaaacaaggaggcaactgagggaaaatgctgaagacatgggcaat',...
            'ggttgcttcaaaatataccacaaatgtgacaacgcatgcatagagtcaatcagaaatggg',...
            'acttatgaccatgatgtatacagagacgaagcattaaacaaccggtttcagatcaaaggt',...
            'gttgaactgaagtctggatacaaagactggatcctgtggatttcctttgccatatcatgc',...
            'tttttgctttgtgttgttttgctggggttcatcatgtgggcctgccagagaggcaacatt',...
            'aggtgcaacatttgcatttgagtg');
    case 3 %Pa-mCherry
        code=strcat(...
            'ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATTAAGGAGTTCATGCGCTTCAAG',...
            'GTGCACATGGAGGGGTCCGTGAACGGCCACGTGTTCGAGATCGAGGGCGAGGGCGAGGGCC',...
            'GCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGCGGCCCCCTGCCCTT',...
            'CACCTGGGACATCCTGAGCCCTCAGTTCATGTACGGCTCCAATGCCTACGTGAAGCACCCC',...
            'GCCGACATCCCCGACTACTTTAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGA',...
            'TGAAATTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCGA',...
            'GTTCATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTGATGCAG',...
            'AAGAAGACCATGGGCTGGGAGGCCCTCTCCGAGCGGATGTACCCCGAGGACGGCGCCCTGA',...
            'AGGGCGAGGTCAAGCCCAGAGTGAAGCTGAAGGACGGCGGCCACTACGACGCTGAGGTCAA',...
            'GACCACCTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAACCGCAAG',...
            'CTGGACATCACCAGCCACAACGAGGACTACACCATCGTGGAGCAGTACGAGAGAGCCGAGG',...
            'GCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGTAA');
    case 4 %Human Actin, beta (ACTB), mRNA NCBI Reference Sequence: NM_001101.3
        code=strcat(...
            'atggatgatgatatcgccgcgctcgtcgtcgacaacggctccggcatgtgcaaggccggc',...
            'ttcgcgggcgacgatgccccccgggccgtcttcccctccatcgtggggcgccccaggcac',...
            'cagggcgtgatggtgggcatgggtcagaaggattcctatgtgggcgacgaggcccagagc',...
            'aagagaggcatcctcaccctgaagtaccccatcgagcacggcatcgtcaccaactgggac',...
            'gacatggagaaaatctggcaccacaccttctacaatgagctgcgtgtggctcccgaggag',...
            'caccccgtgctgctgaccgaggcccccctgaaccccaaggccaaccgcgagaagatgacc',...
            'cagatcatgtttgagaccttcaacaccccagccatgtacgttgctatccaggctgtgcta',...
            'tccctgtacgcctctggccgtaccactggcatcgtgatggactccggtgacggggtcacc',...
            'cacactgtgcccatctacgaggggtatgccctcccccatgccatcctgcgtctggacctg',...
            'gctggccgggacctgactgactacctcatgaagatcctcaccgagcgcggctacagcttc',...
            'accaccacggccgagcgggaaatcgtgcgtgacattaaggagaagctgtgctacgtcgcc',...
            'ctggacttcgagcaagagatggccacggctgcttccagctcctccctggagaagagctac',...
            'gagctgcctgacggccaggtcatcaccattggcaatgagcggttccgctgccctgaggca',...
            'ctcttccagccttccttcctgggcatggagtcctgtggcatccacgaaactaccttcaac',...
            'tccatcatgaagtgtgacgtggacatccgcaaagacctgtacgccaacacagtgctgtct',...
            'ggcggcaccaccatgtaccctggcattgccgacaggatgcagaaggagatcactgccctg',...
            'gcacccagcacaatgaagatcaagatcattgctcctcctgagcgcaagtactccgtgtgg',...
            'atcggcggctccatcctggcctcgctgtccaccttccagcagatgtggatcagcaagcag',...
            'gagtatgacgagtccggcccctccatcgtccaccgcaaatgcttctag');
    case 5 %Dendra2-N
        code=strcat(...
            'ATGAACACCCCGGGAATTAACCTGATCAAGGAGGACATGCGCGTGAAGGTGCACATGGAG',...
            'GGCAACGTGAACGGCCACGCCTTCGTGATCGAGGGCGAGGGCAAGGGCAAGCCCTACGAGG',...
            'GCACCCAGACCGCCAACCTGACCGTGAAGGAGGGCGCCCCCCTGCCCTTCAGCTACGACAT',...
            'CCTGACCACCGCCGTGCACTACGGCAACCGGGTGTTCACCAAGTACCCCGAGGACATCCCC',...
            'GACTACTTCAAGCAGAGCTTCCCCGAGGGCTACAGCTGGGAGCGCACCATGACCTTCGAGG',...
            'ACAAGGGCATCTGCACCATCCGCAGCGACATCAGCCTGGAGGGCGACTGCTTCTTCCAGAA',...
            'CGTGCGCTTCAAGGGCACCAACTTCCCCCCCAACGGCCCCGTGATGCAGAAGAAGACCCTG',...
            'AAGTGGGAGCCCAGCACCGAGAAGCTGCACGTGCGCGACGGCCTGCTGGTGGGCAACATCA',...
            'ACATGGCCCTGCTGCTGGAGGGCGGCGGCCACTACCTGTGCGACTTCAAGACCACCTACAA',...
            'GGCCAAGAAGGTGGTGCAGCTGCCCGACGCCCACTTCGTGGACCACCGCATCGAGATCCTG',...
            'GGCAACGACAGCGACTACAACAAGGTGAAGCTGTACGAGCACGCCGTGGCCCGCTACAGCC',...
            'CCCTGCCCAGCCAGGTGTGGTAA');
    case 6 %X-31 Neuraminidase (NA)
        code=strcat(...
            'ATGAATCCAAATCAAAAGATAATAACAATTGGCTCTGTCTCTCTCACCATTGCAACAGTATGCTTCCTCA',...
            'TGCAGATTGCCATCCTGGTAACTACTGTAACATTGCATTTTAAGCAATATGAGTGCGACTCCCCCGCGAG',...
            'CAACCAAGTAATGCCGTGTGAACCAATAATAATAGAAAGGAACATAACAGAGATAGTGTATTTGAATAAC',...
            'ACCACCATAGAGAAAGAGATATGCCCCAAAGTAGTGGAATACAGAAATTGGTCAAAGCCGCAATGTCAAA',...
            'TTACAGGATTTGCACCTTTTTCTAAGGACAATTCAATCCGGCTTTCTGCTGGTGGGGACATTTGGGTGAC',...
            'GAGAGAACCTTATGTGTCATGCGATCATGGCAAGTGTTATCAATTTGCACTCGGGCAGGGGACCACACTA',...
            'GACAACAAACATTCAAATGACACAATACATGATAGAATCCCTCATCGAACCCTATTAATGAATGAGTTGG',...
            'GTGTTCCATTTCATTTAGGAACCAGGCAAGTGTGTATAGCATGGTCCAGCTCAAGTTGTCACGATGGAAA',...
            'AGCATGGCTGCATGTTTGTATCACTGGGGATGACAAAAATGCAACTGCTAGCTTCATTTATGACGGGAGG',...
            'CTTGTGGACAGTATTGGTTCATGGTCTCAAAATATCCTCAGAACCCAGGAGTCGGAATGCGTTTGTATCA',...
            'ATGGGACTTGCACAGTAGTAATGACTGATGGAAGTGCTTCAGGAAGAGCCGATACTAGAATACTATTCAT',...
            'TGAAGAGGGGAAAATTGTCCATATTAGCCCATTGTCAGGAAGTGCTCAGCATGTAGAAGAGTGTTCCTGT',...
            'TATCCTAGATATCCTGGCGTCAGATGTATCTGCAGAGACAACTGGAAAGGCTCTAATAGGCCCGTCGTAG',...
            'ACATAAATATGGAAGATTATAGCATTGATTCCAGTTATGTGTGCTCAGGGCTTGTTGGCGACACACCTAG',...
            'AAACGACGACAGATCTAGCAATAGCAATTGCAGGAATCCTAATAATGAGAGAGGGAATCAAGGAGTGAAA',...
            'GGCTGGGCCTTTGACAATGGAGATGACGTGTGGATGGGAAGAACGATCAGCAAGGATTTACGCTCAGGTT',...
            'ATGAAACTTTCAAAGTCATTGGTGGTTGGTCCACACCTAATTCCAAATCGCAGATCAATAGACAAGTCAT',...
            'AGTTGACAGCGATAATCGGTCAGGTTACTCTGGTATTTTCTCTGTTGAGGGCAAAAGCTGCATCAATAGG',...
            'TGCTTTTATGTGGAGTTGATAAGGGGAAGGAAACAGGAGACTAGAGTGTGGTGGACCTCAAACAGTATTG',...
            'TTGTGTTTTGTGGCACTTCAGGTACCTATGGAACAGGCTCATGGCCTGATGGGGCGAACATCAATTTCAT',...
            'GCCTATATAA');
    case 7 %Human Cofilin
        code=strcat(...
            'ATGGCCTCCGGTGTGGCTGTCTCTGATGGTGTCATCAAGGTGTTCAACGACATGAAGG',...
            'TGCGTAAGTCTTCAACGCCAGAGGAGGTGAAGAAGCGCAAGAAGGCGGTGCTCTTCTGC',...
            'CTGAGTGAGGACAAGAAGAACATCATCCTGGAGGAGGGCAAGGAGATCCTGGTGGGCGA',...
            'TGTGGGCCAGACTGTCGACGACCCCTACGCCACCTTTGTCAAGATGCTGCCAGATAAGG',...
            'ACTGCCGCTATGCCCTCTATGATGCAACCTATGAGACCAAGGAGAGCAAGAAGGAGGATC',...
            'TGGTGTTTATCTTCTGGGCCCCCGAGTCTGCGCCCCTTAAGAGCAAAATGATTTATGCCA',...
            'GCTCCAAGGACGCCATCAAGAAGAAGCTGACAGGGATCAAGCATGAATTGCAAGCAAACT',...
            'GCTACGAGGAGGTCAAGGACCGCTGCACCCTGGCAGAGAAGCTGGGGGGCAGTGCCGTCA',...
            'TCTCCCTGGAGGGCAAGCCTTTG');
    case 8 %Pa-mKate
        code='ATGGTGTCTAAGGGCGAAGAGCTGATTAAGGAGAACATGCACATGAAGCTGTACATGGAGGGCACCGTGAACAACCACCACTTCAAGTGCACATCCGAGGGCGAAGGCAAGCCCTACGAGGGCACCCAGACCATGAGAATCAAGGTGGTCGAGGGCGGCCCTCTCCCCTTCGCCTTCGACATCCTGGCTACCAGCTTCATGTACGGCAGCAAGACCTTCATCAACCACACCCAGGGCATCCCCGACTTCTGGAAGCAGTCCTTCCCTGAGGGCTTCACATGGGAGAGAGTCACCACATACGAAGACGGGGGCGTGCTGACCGCTACCCAGGACACCAGCCTCCAGGACGGCTGCCTCATCTACAACGTCAAGATCAGAGGGGTGAACTTCCCATCCAACGGCCCTGTGATGCAGAAGAAAACACTCGGCTGGGAGGCCAACACCGAGATGCTGTACCCCGCTGACGGCGGCCTGGAAGGCAGAGGGGACATGGCCCTGAAGCTCGTGGGCGGGGGCCACCTGATCTGCAACTTGAAGACCACATACAGATCCAAGAAACCCGCTAAGAACCTCAAGATGCCCGGCGTCTACTATGTGGACCGCAGACTGGAAAGAATCAAGGAGGCCGACAAAGAGACCTACGTCGAGCAGCACGAGGTGGCTGTGGCCAGATACTGCGACCTCCCTAGCAAACTGGGGCACAAGCTTAATTAA';
    case 9% Human Profilin
        code='ATGGCCGGGTGGAACGCCTACATCGACAACCTCATGGCGGACGGGACCTGTCAGGACGCGGCCATCGTGGGCTACAAGGACTCGCCCTCCGTCTGGGCCGCCGTCCCCGGGAAAACGTTCGTCAACATCACGCCAGCTGAGGTGGGTGTCCTGGTTGGCAAAGACCGGTCAAGTTTTTACGTGAATGGGCTGACACTTGGGGGCCAGAAATGTTCGGTGATCCGGGACTCACTGCTGCAGGATGGGGAATTTAGCATGGATCTTCGTACCAAGAGCACCGGTGGGGCCCCCACCTTCAATGTCACTGTCACCAAGACTGACAAGACGCTAGTCCTGCTGATGGGCAAAGAAGGTGTCCACGGTGGTTTGATCAACAAGAAATGTTATGAAATGGCCTCCCACCTTCGGCGTTCCCAGTACTGA';
    case 10% Human Tropomyosin 1 alpha variant 2 NM_001018007.1
        code=strcat('1 atggacgcca tcaagaagaa gatgcagatg ctgaagctcg acaaggagaa cgccttggat',...
'       61 cgagctgagc aggcggaggc cgacaagaag gcggcggaag acaggagcaa gcagctcgag',...
'      121 gaggacatcg cggccaagga gaagttgctg cgggtgtcgg aggacgagcg ggaccgggtg',...
'      181 ctggaggagc tgcacaaggc ggaggacagc ctcctggccg ccgaagaggc cgccgccaag',...
'      241 gctgaagccg acgtagcttc tctgaacaga cgcatccagc tggttgagga agagttggat',...
'      301 cgtgcccagg agcgtctggc aacagctttg cagaagctgg aggaagctga gaaggcagca',...
'      361 gatgagagtg agagaggcat gaaagtcatt gagagtcgag cccaaaaaga tgaagaaaaa',...
'      421 atggaaattc aggagatcca actgaaagag gccaagcaca ttgctgaaga tgccgaccgc',...
'      481 aaatatgaag aggtggcccg taagctggtc atcattgaga gcgacctgga acgtgcagag',...
'      541 gagcgggctg agctctcaga aggcaaatgt gccgagcttg aagaagaatt gaaaactgtg',...
'      601 acgaacaact tgaagtcact ggaggctcag gctgagaagt actcgcagaa ggaagacaga',...
'      661 tatgaggaag agatcaaggt cctttccgac aagctgaagg aggctgagac tcgggctgag',...
'      721 tttgcggaga ggtcagtaac taaattggag aaaagcattg atgacttaga agagaaagtg',...
'      781 gctcatgcca aagaagaaaa ccttagtatg catcagatgc tggatcagac tttactggag',...
'      841 ttaaacaaca tgtga');

    case 11% Human Tropomyosin 3 variant 2 NM_153649 
        code=strcat('1 atggctggga tcaccaccat cgaggcggtg aagcgcaaga tccaggttct gcagcagcag',...
'       61 gcagatgatg cagaggagcg agctgagcgc ctccagcgag aagttgaggg agaaaggcgg',...
'      121 gcccgggaac aggctgaggc tgaggtggcc tccttgaacc gtaggatcca gctggttgaa',...
'      181 gaagagctgg accgtgctca ggagcgcctg gccactgccc tgcaaaagct ggaagaagct',...
'      241 gaaaaagctg ctgatgagag tgagagaggt atgaaggtta ttgaaaaccg ggccttaaaa',...
'      301 gatgaagaaa agatggaact ccaggaaatc caactcaaag aagctaagca cattgcagaa',...
'      361 gaggcagata ggaagtatga agaggtggct cgtaagttgg tgatcattga aggagacttg',...
'      421 gaacgcacag aggaacgagc tgagctggca gagtcccgtt gccgagagat ggatgagcag',...
'      481 attagactga tggaccagaa cctgaagtgt ctgagtgctg ctgaagaaaa gtactctcaa',...
'      541 aaagaagata aatatgagga agaaatcaag attcttactg ataaactcaa ggaggcagag',...
'      601 acccgtgctg agtttgctga gagatcggta gccaagctgg aaaagacaat tgatgacctg',...
'      661 gaagataaac tgaaatgcac caaagaggag cacctctgta cacaaaggat gctggaccag',...
'      721 accctgcttg acctgaatga gatgtag');
    case 12 %EGFP - U57609.1
        code=strcat('atggtg agcaagggcg aggagctgtt caccggggtg gtgcccatcc',...
'       721 tggtcgagct ggacggcgac gtaaacggcc acaagttcag cgtgtccggc gagggcgagg',...
'       781 gcgatgccac ctacggcaag ctgaccctga agttcatctg caccaccggc aagctgcccg',...
'       841 tgccctggcc caccctcgtg accaccctga cctacggcgt gcagtgcttc agccgctacc',...
'       901 ccgaccacat gaagcagcac gacttcttca agtccgccat gcccgaaggc tacgtccagg',...
'       961 agcgcaccat cttcttcaag gacgacggca actacaagac ccgcgccgag gtgaagttcg',...
'      1021 agggcgacac cctggtgaac cgcatcgagc tgaagggcat cgacttcaag gaggacggca',...
'      1081 acatcctggg gcacaagctg gagtacaact acaacagcca caacgtctat atcatggccg',...
'      1141 acaagcagaa gaacggcatc aaggtgaact tcaagatccg ccacaacatc gaggacggca',...
'      1201 gcgtgcagct cgccgaccac taccagcaga acacccccat cggcgacggc cccgtgctgc',...
'      1261 tgcccgacaa ccactacctg agcacccagt ccgccctgag caaagacccc aacgagaagc',...
'      1321 gcgatcacat ggtcctgctg gagttcgtga ccgccgccgg gatcactctc ggcatggacg',...
'      1381 agctgtacaa gtaa');

    otherwise
        code='___';
        

end

