function [ POI chunksize ] = lookforgoodchunks( xmatch,threshold )
%lookforgoodchunks by Philip Andresen (Version 23:AUGUST:2011)
%INTENDED CALLER: align_DNA.m
%PURPOSE: This program is essentially a one dimensional cluster analysis
%   tool. It takes a binary file and searches for chunks of ones that are
%   all right next to eachother. It returns two arrays of the points of
%   interest (the beginning indecies of the chunks) and the chunk widths.
%   It ignores chunks that are smaller than (threshold) indexes wide.
%INPUTS:
%   xmatch: The input binary array, generated by DNA_reader usually and
%       passed to align_DNA which passes it here.
%   threshold: The minimum chunk size.
%OUTPUTS:
%   POI: An array of the chunk beginning locations
%   Chunksize: An array of the chunk widths.
%CHANGELOG:
%   Changes made on (23:AUGUST:2011)
%   Changed < to <= to prevent loops from ending early
%   Changes were marked as comments in the file.
%   Added one line to fix the final nucleotide from being removed.
%External function dependencies:
%   None
%SPECIAL NOTES: 
%   None
currentsize=0;
chunksize=0;
POI=0;
ind=1;
chunk_number=1;
%FIND THE POINTS OF INTEREST
while ind+currentsize<=length(xmatch);%changed to <= from <
    if xmatch(ind)==1;
        while xmatch(ind+currentsize)==1;
            if ind+currentsize>=length(xmatch);
                currentsize=currentsize+1; %added this line(23:AUGUST:2011)
                break;
            else
                currentsize=currentsize+1;
            end;
        end;
        %currentsize=currentsize+1; %uncommethed
    end;
    if currentsize>threshold;
        POI(chunk_number)=ind;
        chunksize(chunk_number)=currentsize-1; %Currentsize+0 includes one bad point at the end.
        chunk_number=chunk_number+1;
        %disp(currentsize)
    end;
    %if currentsize<0; currentsize=0; end;
    ind=ind+currentsize+1;
    currentsize=0;
end;
% if POI~=1;
%     POIS=[POIS POI];
% end;
%END POINTS OF INTEREST
end

